// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	workers "github.com/hyonosake/HTTP-Multiplexer/internal/workers"
	mock "github.com/stretchr/testify/mock"
)

// WorkerPool is an autogenerated mock type for the WorkerPool type
type WorkerPool struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: job
func (_m *WorkerPool) AddTask(job workers.WorkerJob) {
	_m.Called(job)
}

// Close provides a mock function with given fields:
func (_m *WorkerPool) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunWorkers provides a mock function with given fields: ctx
func (_m *WorkerPool) RunWorkers(ctx context.Context) {
	_m.Called(ctx)
}
