version: "3.9"
services:
  server:
    container_name: HTTP-Multiplexer
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    restart: on-failure
    ports:
      - "1234:1234"