apiVersion: v1
kind: Service
metadata:
    name: myName
    namespace: default
    labels:
        router.deis.io/routable: "true"
    annotations:
        router.deis.io/domains: ""
spec:
    type: NodePort
    selector:
        app: myName
    ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 443